name: h_tracker
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  flutter_signin_button: ^2.0.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  go_router: ^14.1.4
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
